// DerbySystem — runtime config
// This file is gitignored. Set your Supabase credentials here.
// For GitHub Pages deployments, this file is generated by the setup wizard
// or you can fill it in manually.
window.DS_CONFIG = {
  url:      "https://mxluynorztkbkrbdzitj.supabase.co",
  anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14bHV5bm9yenRrYmtyYmR6aXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTQxMDQsImV4cCI6MjA4ODIzMDEwNH0.yQgVOtPBbiWQcSN7lLYofU8rOladOL5KRlWqiNGLW08",
};
